### ISSUE TITLE
cert-manager: Nil pointer error on Helm chart upgrade

### ISSUE THREAD

**Issue by fmunteanu** [axivo/k3s-cluster#147]
### Existing Issues

- [X] I have searched the existing issues

### What Happened

During the Helm chart upgrade from 1.14.5 to 1.15.0, the following error message is encountered:

```
  command: /usr/sbin/helm upgrade --version=v1.15.0 -i --reuse-values=true --wait cert-manager 'jetstack/cert-manager'
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout:
    stderr: Error: UPGRADE FAILED: template: cert-manager/templates/crds.yaml:1:6: executing "cert-manager/templates/crds.yaml" at <include "cert-manager.crd-check" .>: error calling include: template: cert-manager/templates/_helpers.tpl:196:43: executing "cert-manager.crd-check" at <.Values.crds.enabled>: nil pointer evaluating interface {}.enabled
```

### Kernel Version

```shell
Linux apollo 6.8.0-1005-raspi #5-Ubuntu SMP PREEMPT_DYNAMIC Wed May 22 15:01:35 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```shell
Client Version: v1.29.4+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4+k3s1
```

### Code of Conduct

- [X] I agree to follow project's Code of Conduct
