### ISSUE TITLE
Cilium: Release 1.16 upgrade fails with "no_pool" message

### ISSUE THREAD

**Issue by fmunteanu** [axivo/k3s-cluster#211]
### Existing Issues

- [X] I have searched the existing issues

### What Happened

Upgrading from release 1.15 to 1.16 fails with following `cilium-ingress` message:

```
status:
  loadBalancer: {}
  conditions:
    - type: cilium.io/IPAMRequestSatisfied
      status: 'False'
      lastTransitionTime: '2024-09-12T08:13:20Z'
      reason: no_pool
      message: No pool exists with a CIDR containing '192.168.4.17'
```

### Kernel Version

```shell
Linux apollo 6.8.0-1010-raspi #11-Ubuntu SMP PREEMPT_DYNAMIC Thu Aug  8 23:22:41 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

### Kubernetes Version

```shell
Client Version: v1.30.4+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4+k3s1
```

### Code of Conduct

- [X] I agree to follow project's Code of Conduct
