### ISSUE TITLE
Cilium BGP support

### ISSUE THREAD

**Issue by fmunteanu** [axivo/k3s-cluster#46]
### Existing Issues

- [X] I have searched the existing issues

### Related Problem

I'm waiting on UniFi to release the BGP feature for UDM SE, they made a reference into their Network [8.1.113 release](https://community.ui.com/releases/UniFi-Network-Application-8-1-113/af46fd38-8afe-4cef-8de1-89636b02b52c#), planned to be released with Network 8.2. Once released, I will be able to test and implement Cilium's [BGP Control Plane](https://docs.cilium.io/en/stable/network/bgp-control-plane/). 

### Solution Implementation

Implementation example, to expose `kube-apiserver`:

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.4.15
  name: cilium-api-server
  namespace: kube-system
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: io.cilium/bgp-control-plane
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 6443
  selector:
    k8s-app: kube-apiserver
    tier: control-plane
  type: LoadBalancer
```

### Code of Conduct

- [X] I agree to follow project's Code of Conduct
